### ISSUE TITLE
"features" list should link to the documentation for said feature.

### ISSUE THREAD

**Issue by AshKyd** [mochajs/mochajs.github.io#21]
Invariably when I land on the Mocha site and search for a thing, I land on the "Features" list and am dismayed that it's not clickable. IMO the features list should link to the relevant feature docs, similar to the TOC.

![image](https://cloud.githubusercontent.com/assets/49600/11829607/4f1d8cb0-a3e9-11e5-99de-5975c7c6a5ff.png)

I'm happy to look into this if there's no objections.

**Comment by hollomancer** [comment]
@AshKyd - still interested in looking into this?

**Comment by boneskull** [comment]
This issue was moved to mochajs/mocha#3135
