### ISSUE TITLE
Support Wallaby.js

### ISSUE THREAD

**Issue by boneskull** [mochajs/mochajs.github.io#3]
@DenisGorbachev writes:

> http://mochajs.org/#editor-plugins — it would be great if you had mentioned Wallaby.js with an intro video here. Much better than default JetBrains test runner.

**Comment by ArtemGovorov** [comment]
A sample project for node.js testing with wallaby.js and mocha can be found in [this repo](https://github.com/wallabyjs/wallaby-node-iojs-sample), browser testing sample for mocha + chai [can be found here](https://github.com/wallabyjs/public/tree/master/sample/jetbrains).

**Comment by ArtemGovorov** [comment]
Created [the pull request](https://github.com/mochajs/mochajs.github.io/pull/11) with a note about wallaby.js in the Editor Plugins doc section.

**Comment by dasilvacontin** [comment]
Closed via https://github.com/mochajs/mochajs.github.io/pull/11.
