### ISSUE TITLE
Consider relicencing mochajs.org's source 

### ISSUE THREAD

**Issue by boneskull** [mochajs/mochajs.github.io#4]
from mochajs/mocha#1783

relevant:

> in summary:
> - The current site is not licensed
> - Therefore nobody can use or modify it in any way
> - Furthermore, anyone who forked Mocha and checked out the gh-pages branch could be sued by TJ
> - We should license it for reuse
> - We can't license it MIT, because MIT applies to software only
> - So let's license it under a CC license
> - TJ will still retain copyright, but the CC license cannot be revoked

**Comment by dasilvacontin** [comment]
@boneskull so I guess your email didn't reach him in the end?

**Comment by boneskull** [comment]
There was no bounce but no reply either. 

At any rate, because of this, we basically need to write the docs from scratch; we cannot relicense. 

The resulting docs should be released under CC. The copyright would be owned by whoever helped make the docs. For simplification, probably display as "Copyright  <year> mochajs.org contributors"

**Comment by boneskull** [comment]
he released it to CC
