### ISSUE TITLE
Display option names in lowercase

### ISSUE THREAD

**Issue by Alhadis** [mochajs/mochajs.github.io#51]
Caps... erm, _probably_ aren't the best design choice for case-sensitive material:

<img src="https://cloud.githubusercontent.com/assets/2346707/17625967/810a9f84-60ee-11e6-8d3c-3825d57c5db2.png" width="290" alt="Figure 1" />

<i>"Wait, which one is `-r` and which is `-R`?"</i>

**Comment by boneskull** [comment]
my bad.
