### ISSUE TITLE
Need test run command in Getting Started

### ISSUE THREAD

**Issue by bdharris08** [mochajs/mochajs.github.io#57]
https://mochajs.org/#getting-started

**Problem**: getting started has you install mocha locally, make a test dir, and write a test, but doesn't show you how to run it nor how to set up npm test.

**Suggestion**: instruct users to add a test script to package.json such as: 
If mocha is installed locally:
`"scripts": {
    "test": "./node_modules/mocha/bin/mocha"
  },`
If mocha is installed globally:
`"scripts": {
    "test": "mocha"
  },`
And then run it with `$ npm test`

**Expected**: some instruction on how to run tests after installing mocha.
**Current**: 
<img width="572" alt="screen shot 2016-10-18 at 3 32 11 pm" src="https://cloud.githubusercontent.com/assets/1817881/19495223/22bbff98-9548-11e6-82fd-dc5764b4c68a.png">

**Comment by ScottFreeCode** [comment]
See also https://github.com/mochajs/mocha/issues/2282#issuecomment-253162837
