### ISSUE TITLE
increase font size

### ISSUE THREAD

**Issue by boneskull** [mochajs/mochajs.github.io#63]
I've read in a couple articles about font sizes on the web, and it occurs to me that the font sizes used on the site are probably too small.  The main text is 14px.  I would like to increase this to 16px (or whatever `em` that typically works out to).  The "code" text is 12px, I believe, and should be as close to the main text in size as is feasible (I think?).

Any other opinions?

**Comment by bdharris08** [comment]
Did  quick survey of other doc's pages:
- [Express.js splash page](http://expressjs.com/) - text in the 4 horizontal boxes is 12px
- [Express.js getting started](http://expressjs.com/en/starter/installing.html) - text is 14px, code is 14px with 1.5 line-height (compared to mocha's 1.25)
- [jest](https://facebook.github.io/jest/) - text is 16px, code is 13px with 1 line height
- [react](https://facebook.github.io/react/) - text is 16px, code seems to be 14px.

Personally, I have to run around the web at 110% magnification or more, so larger font is more friendly, as long as it doesn't clutter up the page.

**Comment by bdharris08** [comment]
and here's what it looks like with html:16/1.6 and code 14/2.0

<img width="979" alt="screen shot 2016-11-04 at 10 11 23 am" src="https://cloud.githubusercontent.com/assets/1817881/20010690/1b8919a4-a277-11e6-8c4e-022320ef17ba.png">

**Comment by ScottFreeCode** [comment]
Re. the screenshot: Is there any way to get the image to scale to the original size on displays of various resolutions?

Re. the issue: Would having a more legible font help also?
