### ISSUE TITLE
responsive site

### ISSUE THREAD

**Issue by boneskull** [mochajs/mochajs.github.io#68]
it should work and look better on mobile and older browsers. 
also: accessibility. 
wham bam

**Comment by gakimball** [comment]
Hey there! [I did a pass on the mobile CSS](https://github.com/gakimball/mochajs.github.io) which I can submit as a PR shortly.

As far as older browsers, how far back specifically were you thinking? The site's layout is fairly simple, so I'm curious to know if you've gotten reports of it not working well in older browsers. (Or if traffic to the site shows that the support is still needed.)

I can also look at the accessibility of the site. If I tackle all three of these things, would you like them all as separate pull requests?

💕 Mocha so I'm trying to give back in a small way. :)
