### ISSUE TITLE
Update for Mocha 4.x line

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mochajs.github.io#81]
The section that's a copy of `mocha --help` needs to be updated, as must the detailed explanation of `--no-exit` (now `--exit`), if nothing else. Helps with mochajs/mocha#3044

**Comment by boneskull** [comment]
- [x] Update "Usage"
- [x] Add `--compilers` deprecation note
- [x] Add info about `--exit`

**Comment by boneskull** [comment]
[Here you go](https://mochajs.org/#--exit----no-exit)
