### ISSUE TITLE
Documented Undocumented Reporters

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mochajs.github.io#83]
https://mochajs.org/#undocumented-reporters documents the XUnit reporter. Instead of the section being labelled "XUnit", it is labelled "Undocumented Reporters". Since the section documents the XUnit reporter, the XUnit reporter is not undocumented as the section name implies.

Amusing anecdote: this reminds me somewhat of the Liar Paradox, but I think it can be resolved without needing to understand the Incompleteness Theorem. (...It is possible I am using a non-standard implementation of the amusement module...)

**Comment by boneskull** [comment]
This issue was moved to mochajs/mocha#3131
